## HW5

### 1. Найдите посредством NumPy SVD для матрицы:

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

In [3]:
print(A)

[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [4]:
U, D, V = np.linalg.svd(A)
U

array([[ 0.17056501,  0.15680918, -0.53077508, -0.79905375, -0.16158397],
       [ 0.39287016, -0.52933945,  0.6134793 , -0.43375771,  0.03082495],
       [-0.14366152, -0.82449256, -0.52379105,  0.14049848,  0.07400343],
       [ 0.88843702,  0.06074346, -0.24655277,  0.37755832, -0.06042632],
       [ 0.08125046,  0.10831843, -0.08231425, -0.10524851,  0.98173958]])

In [5]:
D

array([8.82486885, 6.14060608, 2.53271528])

In [6]:
V

array([[ 0.07116451,  0.71702467,  0.69340553],
       [-0.36737824,  0.66514082, -0.65009301],
       [-0.92734505, -0.20847855,  0.31075368]])

In [7]:
V = V.T
V

array([[ 0.07116451, -0.36737824, -0.92734505],
       [ 0.71702467,  0.66514082, -0.20847855],
       [ 0.69340553, -0.65009301,  0.31075368]])

### 2. Для матрицы из предыдущего задания найдите:

а) евклидову норму;

б) норму Фробениуса.

### Норма Евклида

In [11]:
D[0]
np.linalg.norm(A, ord=2)

8.824868854820444

### Норма Фробениуса

In [9]:
np.sqrt(np.sum(A**2))
np.sqrt(np.sum(D**2))
np.linalg.norm(A)

11.045361017187261